import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger,
  DialogDescription 
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Download, FileText, RefreshCw } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface ComplexityScore {
  overall: number;
  linguistic: number;
  structural: number;
  semantic: number;
  creative: number;
  grade: string;
  insights: string[];
  suggestions: string[];
  timestamp?: Date;
}

interface PDFDownloadButtonProps {
  complexityScore: ComplexityScore;
  originalLyrics: string;
  improvedLyrics?: string;
  className?: string;
}

export default function PDFDownloadButton({
  complexityScore,
  originalLyrics,
  improvedLyrics,
  className
}: PDFDownloadButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [songTitle, setSongTitle] = useState('');
  const [artistName, setArtistName] = useState('');
  const [includeImproved, setIncludeImproved] = useState(!!improvedLyrics);
  const [includeInsights, setIncludeInsights] = useState(true);

  const { toast } = useToast();

  const generatePDFContent = () => {
    const timestamp = new Date().toLocaleString();
    const date = new Date().toISOString().split('T')[0];
    
    let content = `MUSAIX RAP PRO - LYRIC COMPLEXITY ANALYSIS REPORT
Generated: ${timestamp}

`;

    if (songTitle || artistName) {
      content += `SONG INFORMATION
`;
      if (songTitle) content += `Title: ${songTitle}\n`;
      if (artistName) content += `Artist: ${artistName}\n`;
      content += `\n`;
    }

    content += `COMPLEXITY ANALYSIS
Overall Score: ${complexityScore.overall}/100 (Grade: ${complexityScore.grade})

Detailed Breakdown:
• Linguistic Complexity: ${complexityScore.linguistic}/100
• Structural Complexity: ${complexityScore.structural}/100
• Semantic Depth: ${complexityScore.semantic}/100
• Creative Innovation: ${complexityScore.creative}/100

`;

    content += `ORIGINAL LYRICS
${originalLyrics}

`;

    if (improvedLyrics && includeImproved) {
      content += `AI-ENHANCED LYRICS
${improvedLyrics}

`;
    }

    if (includeInsights) {
      if (complexityScore.insights.length > 0) {
        content += `AI INSIGHTS
`;
        complexityScore.insights.forEach(insight => {
          content += `• ${insight}\n`;
        });
        content += `\n`;
      }

      if (complexityScore.suggestions.length > 0) {
        content += `IMPROVEMENT SUGGESTIONS
`;
        complexityScore.suggestions.forEach(suggestion => {
          content += `• ${suggestion}\n`;
        });
        content += `\n`;
      }
    }

    content += `---
Report generated by Musaix Rap Pro
AI-Powered Lyric Enhancement Platform
`;

    return content;
  };

  const downloadPDF = async () => {
    setIsGenerating(true);
    
    try {
      const content = generatePDFContent();
      
      // Create a blob with the content
      const blob = new Blob([content], { type: 'text/plain' });
      
      // Create download link
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = songTitle 
        ? `musaix-${songTitle.toLowerCase().replace(/\s+/g, '-')}-complexity-report-${timestamp}.txt`
        : `musaix-complexity-report-${timestamp}.txt`;
      
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Report Downloaded",
        description: "Your complexity analysis report has been downloaded successfully.",
      });
      
      setIsOpen(false);
    } catch (error) {
      toast({
        title: "Download Failed",
        description: "Failed to generate the report. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className={className}>
          <Download className="h-4 w-4 mr-2" />
          Download Report
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-[#FF4081]" />
            Download Analysis Report
          </DialogTitle>
          <DialogDescription>
            Generate a comprehensive report of your lyric complexity analysis.
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4">
          {/* Song Information */}
          <div className="space-y-3">
            <Label className="text-white font-medium">Song Information (Optional)</Label>
            <div className="space-y-2">
              <Input
                placeholder="Song title"
                value={songTitle}
                onChange={(e) => setSongTitle(e.target.value)}
                className="bg-gray-800 border-gray-700 text-white"
              />
              <Input
                placeholder="Artist name"
                value={artistName}
                onChange={(e) => setArtistName(e.target.value)}
                className="bg-gray-800 border-gray-700 text-white"
              />
            </div>
          </div>

          {/* Report Options */}
          <div className="space-y-3">
            <Label className="text-white font-medium">Report Contents</Label>
            <div className="space-y-2">
              {improvedLyrics && (
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="include-improved"
                    checked={includeImproved}
                    onCheckedChange={setIncludeImproved}
                  />
                  <Label htmlFor="include-improved" className="text-sm text-gray-300">
                    Include AI-enhanced lyrics
                  </Label>
                </div>
              )}
              
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="include-insights"
                  checked={includeInsights}
                  onCheckedChange={setIncludeInsights}
                />
                <Label htmlFor="include-insights" className="text-sm text-gray-300">
                  Include AI insights and suggestions
                </Label>
              </div>
            </div>
          </div>

          {/* Score Summary */}
          <div className="bg-gray-800/50 p-3 rounded-lg">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm text-gray-300">Overall Score</span>
              <Badge className="bg-[#FF4081] text-white">
                {complexityScore.grade}
              </Badge>
            </div>
            <div className="text-lg font-bold text-white">
              {complexityScore.overall}/100
            </div>
          </div>

          {/* Download Button */}
          <Button 
            onClick={downloadPDF} 
            disabled={isGenerating}
            className="w-full musaix-gradient-button"
          >
            {isGenerating ? (
              <>
                <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                Generating Report...
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                Download Report
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}